### ISSUE TITLE
Publish the theme to Open VSX Registry

### ISSUE THREAD

**Issue by MindTooth** [srcery-colors/srcery-vscode#12]
Using VSCodium, I'm unable to find Srcery.  I believe that it needs to be added to https://open-vsx.org too.

I can look into this myself if necessary.

@gagbo thoughts?

**Comment by gagbo** [comment]
Yeah nothing wrong with this. I haven't used VSC.* editors in a while though, so I probably lost all the relevant keys to publish somewhere. I'll try to do this over the winter break at some point
