### ISSUE TITLE
Inverted dimming in titlebar

### ISSUE THREAD

**Issue by Sangeppato** [srcery-colors/srcery-vscode#2]
Currently if the main window is in focus, the font in the titlebar will be dimmed, while when the window is in the background the title is bright. Is this a design choice? In my opinion, the opposite would make more sense.

**Comment by gagbo** [comment]
Hello !
Can you give a screenshot ? This is probably something I overlooked, but I'm not sure yet which property I should modify to fix this.

**Comment by Sangeppato** [comment]
Hi, sorry, I should have included some screenshots in the first post.

Here is when the window is in focus (dimmed font):
![Annotation 2019-11-20 191015](https://user-images.githubusercontent.com/37263823/69265463-97b86e80-0bc9-11ea-918c-925a2a697e0f.png)

And here when it's in the background (bright font):
![Annotation 2019-11-20 191049](https://user-images.githubusercontent.com/37263823/69265470-9a1ac880-0bc9-11ea-9e49-96bc7a5f6d98.png)

**Comment by gagbo** [comment]
Oh my, yeah that should definitely be reverted, I'll try to get it done this week or week-end.

for the time being, you can customize the theme and set yourself values for :

- `titleBar.activeBackground`: Title Bar background when the window is active.
- `titleBar.activeForeground`: Title Bar foreground when the window is active.
- `titleBar.inactiveBackground`: Title Bar background when the window is inactive.
- `titleBar.inactiveForeground`: Title Bar foreground when the window is inactive.
- `titleBar.border`: Title bar border color.

**Comment by gagbo** [comment]
This has been fixed in v0.3.5 Don't hesitate to reopen the issue if you still have the problem
